# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170129_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.date(2017, 2, 9)),
            preserve_default=False,
        ),
    ]
